services:
  - type: web
    name: todo-backend
    env: docker
    plan: free
    region: frankfurt
    rootDir: "."
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 8080
      - key: ALLOWED_ORIGINS
        value: "*"

  - type: web
    name: todo-frontend
    env: node
    plan: free
    region: frankfurt
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://todo-backend.onrender.com
